apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: hms-api-postgres
spec:
  replicas: 1
  selector:
    name: hms-api-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: hms-api-postgres
    spec:
      containers:
      - env:
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: hms-secrets
              key: POSTGRES_DB
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              name: hms-secrets
              key: POSTGRES_USER
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hms-secrets
              key: POSTGRES_PASSWORD
        image: 'registry.access.redhat.com/rhscl/postgresql-10-rhel7:latest'
        name: hms-api-postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: hms-api-postgres-data
      volumes:
      - name: hms-api-postgres-data
        persistentVolumeClaim:
          claimName: hms-api-postgres-data
  triggers:
  - type: ConfigChange