kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: www
spec:
  replicas: 1
  selector:
    name: www
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - www
        from:
          kind: ImageStreamTag
          name: www:latest
          namespace: f15899-tools
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
    name: www
spec:
  host: talent.digital.gov.bc.ca