import { registerEnumType } from '@nestjs/graphql';

export enum SkillCategory {
  CLOUD_PLATFORMS = 'CLOUD_PLATFORMS',
  COMMUNICATION = 'COMMUNICATION',
  CONTAINER_PLATFORMS = 'CONTAINER_PLATFORMS',
  DATABASES = 'DATABASES',
  DEVELOPMENT_TOOLS = 'DEVELOPMENT_TOOLS',
  FRAMEWORKS_AND_LIBRARIES = 'FRAMEWORKS_AND_LIBRARIES',
  KNOWLEDGE = 'KNOWLEDGE',
  OPERATING_SYSTEMS = 'OPERATING_SYSTEMS',
  PRODUCTIVITY = 'PRODUCTIVITY',
  PROGRAMMING_LANGUAGES = 'PROGRAMMING_LANGUAGES',
}

registerEnumType(SkillCategory, { name: 'SkillCategory', description: undefined });
