apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: hms-backend-eventstore
spec:
  replicas: 1
  selector:
    app: hms-backend-eventstore
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: hms-backend-eventstore
    spec:
      containers:
        - name: hms-backend-eventstore
          image: hms-backend-eventstore:latest
          ports:
            - containerPort: 1113
            - containerPort: 2113
          env:
            - name: EVENTSTORE_CLUSTER_SIZE
              value: '1'
            - name: EVENTSTORE_RUN_PROJECTIONS
              value: 'All'
            - name: EVENTSTORE_START_STANDARD_PROJECTIONS
              value: 'true'
            - name: EVENTSTORE_EXT_TCP_PORT
              value: '1113'
            - name: EVENTSTORE_HTTP_PORT
              value: '2113'
            - name: EVENTSTORE_INSECURE
              value: 'true'
            - name: EVENTSTORE_ENABLE_EXTERNAL_TCP
              value: 'true'
            - name: EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP
              value: 'true'
          volumeMounts:
            - name: eventstore-volume-data
              mountPath: /var/lib/eventstore
            - name: eventstore-volume-logs
              mountPath: /var/log/eventstore
      volumes:
        - name: eventstore-volume-data
          persistentVolumeClaim:
            claimName: eventstore-volume-data
        - name: eventstore-volume-logs
          persistentVolumeClaim:
            claimName: eventstore-volume-logs
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - hms-backend-eventstore
        from:
          kind: ImageStreamTag
          name: hms-backend-eventstore:latest
          namespace: f15899-tools
      type: ImageChange
