---
kind: Template
apiVersion: template.openshift.io/v1
parameters:
  - name: NAMESPACE
    displayName: Namespace
    required: true
objects:
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: allow-all-ingress-www
      namespace: ${NAMESPACE}
    spec:
      podSelector:
        matchLabels:
          name: www
      ingress:
        - {}
      policyTypes:
        - Ingress
  - kind: Service
    apiVersion: v1
    metadata:
      name: www
      namespace: ${NAMESPACE}
    spec:
      selector:
        name: www
      ports:
        - name: http
          port: 3000
          targetPort: 3000
