---
kind: Template
apiVersion: template.openshift.io/v1
parameters:
  - name: NAMESPACE
    displayName: Namespace
    required: true
  - name: DOCKER_IMAGE_TAG
    displayName: Docker Image Tag
    description: 'The tag to pull, eg: develop-latest'
    required: true
objects:
  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      name: www
      namespace: ${NAMESPACE}
    spec:
      replicas: 1
      selector:
        name: www
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - www
            from:
              kind: ImageStreamTag
              name: www:${DOCKER_IMAGE_TAG}
              namespace: ${NAMESPACE}
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            name: www
        spec:
          containers:
            - name: www
              image: ''
              ports:
                - containerPort: 3000
                  protocol: TCP
