version: '3.8'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - postgres
    env_file:
      - .env.docker
    volumes:
      - ./prisma:/usr/src/app/prisma
      - ./src:/usr/src/app/src
      - hms-backend-nodemodules:/node_modules
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - .env
  eventstore:
    build:
      context: ./eventstore
      dockerfile: Dockerfile
    ports:
      - '1113:1113'
      - '2113:2113'
  # Uncomment the following lines to persist data across runs
  # Not required for development where starting from 0 is preferred
  # volumes:
  #   - type: volume
  #     source: eventstore-volume-data
  #     target: /var/lib/eventstore
  #   - type: volume
  #     source: eventstore-volume-logs
  #     target: /var/log/eventstore
# Uncomment the following lines if volumes are uncommented above
volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
  hms-backend-nodemodules:
