version: '3.4'

services:
  eventstore.db:
    container_name: event-store
# Uncomment the following line for arm64
# image: eventstore/eventstore:22.10.2-alpha-arm64v8
# Uncommont the following line for x86-64
    image: eventstore/eventstore:22.10.2-bionic
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - '1113:1113'
      - '2113:2113'
# Uncomment the following lines to persist data across runs
# Not required for development where starting from 0 is preferred
#
#   volumes:
#     - type: volume
#       source: eventstore-volume-data
#       target: /var/lib/eventstore
#     - type: volume
#       source: eventstore-volume-logs
#       target: /var/log/eventstore
#
# volumes:
#   eventstore-volume-data:
#   eventstore-volume-logs: