apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: nestjs-app
spec:
  triggers:
      - imageChangeParams:
          from:
            kind: ImageStreamTag
            name: hms-api:latest
            namespace: f15899-tools
          type: ImageChange
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
    name: nestjs-app
spec:
  host: hms-api.digital.gov.bc.ca
---
#disable the route for prod
$patch: delete
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hms-api-eventstore-route
---
$patch: delete
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-ingress-eventstore
