apiVersion: route.openshift.io/v1
kind: Route
metadata:
    name: nestjs-app
spec:
  host: hms-api.apps.silver.devops.gov.bc.ca
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hms-api-eventstore-route
spec:
  host: hms-eventstore.apps.silver.devops.gov.bc.ca