apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: hms-backend-eventstore
  namespace: f15899-tools
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'hms-backend-eventstore:latest'
  source:
    dockerfile: |
      FROM eventstore/eventstore:22.10.2-bionic
      ENV EVENTSTORE_CLUSTER_SIZE=1
      ENV EVENTSTORE_RUN_PROJECTIONS=All
      ENV EVENTSTORE_START_STANDARD_PROJECTIONS=true
      ENV EVENTSTORE_EXT_TCP_PORT=1113
      ENV EVENTSTORE_HTTP_PORT=2113
      ENV EVENTSTORE_INSECURE=true
      ENV EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      ENV EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    type: Dockerfile
  strategy:
    dockerStrategy:
    type: Docker
