# Use the official Node.js 18 image.
FROM node:18.17.1
# Create and change to the app directory.
WORKDIR /usr/src/app

# Copy application dependency manifests to the container image.
COPY package*.json ./
COPY ../../tsconfig.json ../../tsconfig.json

# Install dependencies.
RUN npm install

# Copy local code to the container image.
COPY . .

# Expose port 4000
EXPOSE 5173

# Start the application
CMD ["npm", "run", "dev"]
