version: '3.8'
services:
  vite_docker:
    build:
      context: ../../
      dockerfile: apps/hms-app/Dockerfile
      args:
        - VITE_BACKEND_URL=http://localhost:4000
        - VITE_KEYCLOAK_REALM_URL=https://dev.loginproxy.gov.bc.ca/auth/realms/standard
        - VITE_KEYCLOAK_CLIENT_ID=digital-talent-hms-app-4960
        - VITE_KEYCLOAK_REDIRECT_URL=https://dt.apps.silver.devops.gov.bc.ca/app/auth/callback
    ports:
      - 5173:5173
    volumes:
      - ./src:/usr/src/app/src
