
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: hms-app
spec:
  # lookupPolicy:
  #   local: true
  tags:
    - name: develop-latest
      from:
        kind: DockerImage
        name: artifacts.developer.gov.bc.ca/tf15-images/hms-app:develop-latest
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
    - name: stage-latest
      from:
        kind: DockerImage
        name: artifacts.developer.gov.bc.ca/tf15-images/hms-app:stage-latest
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
    - name: latest
      from:
        kind: DockerImage
        name: artifacts.developer.gov.bc.ca/tf15-images/hms-app:latest
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
