# Manual started workflow
# This is the simplest for of running the Cypress tests in Github actions
name: e2e-simple
on: [workflow_dispatch, repository_dispatch]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: E2E Smoke tests
        uses: cypress-io/github-action@v5.3.0
        id: smoke
        # Continue the build in case of an error, as we need to set the
        # commit status in the next step, both in case of success and failure
        continue-on-error: true
        with:
          # No recording of results in the cloud
          record: false
          # We need to force the install due to version checking
          install-command: npm ci -f
          working-directory: testing
